CREATE TABLE IF NOT EXISTS clients (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name  VARCHAR(255) NOT NULL,
last_name  VARCHAR(255),
nick_name  VARCHAR(255),
phone  BIGINT,
email VARCHAR(512)
);

CREATE TABLE IF NOT EXISTS transport (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
brand_name VARCHAR(255),
model VARCHAR,
add_inform VARCHAR,
vin VARCHAR,
owner_id BIGINT REFERENCES clients (id) NOT NULL,
gos_number VARCHAR,
year int
);
